# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import desabafo_pb2 as desabafo__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in desabafo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeedStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostDesabafo = channel.unary_unary(
                '/desabafo.Feed/PostDesabafo',
                request_serializer=desabafo__pb2.RascunhoDesabafo.SerializeToString,
                response_deserializer=desabafo__pb2.Desabafo.FromString,
                _registered_method=True)
        self.GetFeed = channel.unary_stream(
                '/desabafo.Feed/GetFeed',
                request_serializer=desabafo__pb2.FeedRequest.SerializeToString,
                response_deserializer=desabafo__pb2.Desabafo.FromString,
                _registered_method=True)


class FeedServicer:
    """Missing associated documentation comment in .proto file."""

    def PostDesabafo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostDesabafo': grpc.unary_unary_rpc_method_handler(
                    servicer.PostDesabafo,
                    request_deserializer=desabafo__pb2.RascunhoDesabafo.FromString,
                    response_serializer=desabafo__pb2.Desabafo.SerializeToString,
            ),
            'GetFeed': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFeed,
                    request_deserializer=desabafo__pb2.FeedRequest.FromString,
                    response_serializer=desabafo__pb2.Desabafo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'desabafo.Feed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('desabafo.Feed', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Feed:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostDesabafo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desabafo.Feed/PostDesabafo',
            desabafo__pb2.RascunhoDesabafo.SerializeToString,
            desabafo__pb2.Desabafo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/desabafo.Feed/GetFeed',
            desabafo__pb2.FeedRequest.SerializeToString,
            desabafo__pb2.Desabafo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
