# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reacoes_pb2 as reacoes__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reacoes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReacaoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarReacoes = channel.stream_unary(
                '/reacoes.ReacaoService/EnviarReacoes',
                request_serializer=reacoes__pb2.ReacaoRequest.SerializeToString,
                response_deserializer=reacoes__pb2.ResumoReacoes.FromString,
                _registered_method=True)
        self.BuscarReacoes = channel.unary_unary(
                '/reacoes.ReacaoService/BuscarReacoes',
                request_serializer=reacoes__pb2.ReacaoConsulta.SerializeToString,
                response_deserializer=reacoes__pb2.ReacaoResposta.FromString,
                _registered_method=True)


class ReacaoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EnviarReacoes(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarReacoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReacaoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarReacoes': grpc.stream_unary_rpc_method_handler(
                    servicer.EnviarReacoes,
                    request_deserializer=reacoes__pb2.ReacaoRequest.FromString,
                    response_serializer=reacoes__pb2.ResumoReacoes.SerializeToString,
            ),
            'BuscarReacoes': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarReacoes,
                    request_deserializer=reacoes__pb2.ReacaoConsulta.FromString,
                    response_serializer=reacoes__pb2.ReacaoResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reacoes.ReacaoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reacoes.ReacaoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReacaoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarReacoes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/reacoes.ReacaoService/EnviarReacoes',
            reacoes__pb2.ReacaoRequest.SerializeToString,
            reacoes__pb2.ResumoReacoes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarReacoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reacoes.ReacaoService/BuscarReacoes',
            reacoes__pb2.ReacaoConsulta.SerializeToString,
            reacoes__pb2.ReacaoResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
