# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: desabafo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'desabafo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65sabafo.proto\x12\x08\x64\x65sabafo\"\x1c\n\x0b\x46\x65\x65\x64Request\x12\r\n\x05quant\x18\x01 \x01(\x03\"!\n\x10RascunhoDesabafo\x12\r\n\x05texto\x18\x01 \x01(\t\"9\n\x08\x44\x65sabafo\x12\r\n\x05texto\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x32~\n\x04\x46\x65\x65\x64\x12>\n\x0cPostDesabafo\x12\x1a.desabafo.RascunhoDesabafo\x1a\x12.desabafo.Desabafo\x12\x36\n\x07GetFeed\x12\x15.desabafo.FeedRequest\x1a\x12.desabafo.Desabafo0\x01\x42\x17Z\x15gen/desabafo;desabafob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desabafo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025gen/desabafo;desabafo'
  _globals['_FEEDREQUEST']._serialized_start=28
  _globals['_FEEDREQUEST']._serialized_end=56
  _globals['_RASCUNHODESABAFO']._serialized_start=58
  _globals['_RASCUNHODESABAFO']._serialized_end=91
  _globals['_DESABAFO']._serialized_start=93
  _globals['_DESABAFO']._serialized_end=150
  _globals['_FEED']._serialized_start=152
  _globals['_FEED']._serialized_end=278
# @@protoc_insertion_point(module_scope)
