# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reacoes.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'reacoes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreacoes.proto\x12\x07reacoes\"$\n\rReacaoRequest\x12\x13\n\x0b\x64\x65sabafo_id\x18\x01 \x01(\t\"\x1e\n\rResumoReacoes\x12\r\n\x05total\x18\x01 \x01(\x05\"%\n\x0eReacaoConsulta\x12\x13\n\x0b\x64\x65sabafo_id\x18\x01 \x01(\t\"$\n\x0eReacaoResposta\x12\x12\n\nquantidade\x18\x01 \x01(\x05\x32\x95\x01\n\rReacaoService\x12\x41\n\rEnviarReacoes\x12\x16.reacoes.ReacaoRequest\x1a\x16.reacoes.ResumoReacoes(\x01\x12\x41\n\rBuscarReacoes\x12\x17.reacoes.ReacaoConsulta\x1a\x17.reacoes.ReacaoRespostaB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reacoes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_REACAOREQUEST']._serialized_start=26
  _globals['_REACAOREQUEST']._serialized_end=62
  _globals['_RESUMOREACOES']._serialized_start=64
  _globals['_RESUMOREACOES']._serialized_end=94
  _globals['_REACAOCONSULTA']._serialized_start=96
  _globals['_REACAOCONSULTA']._serialized_end=133
  _globals['_REACAORESPOSTA']._serialized_start=135
  _globals['_REACAORESPOSTA']._serialized_end=171
  _globals['_REACAOSERVICE']._serialized_start=174
  _globals['_REACAOSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
