syntax = "proto3";

package chat;
option go_package = "gen/chat;chat";


service ChatService {
  // Bidirectional streaming: client and server both send messages freely.
  rpc Chat(stream ChatMessage) returns (stream ChatMessage);

  // Unary helpers (optional but practical)
  rpc JoinRoom  (JoinRequest)  returns (JoinResponse);
  rpc LeaveRoom (LeaveRequest) returns (LeaveResponse);
}

message ChatMessage {
    string message_id = 1;
    string text = 2;
    string room_id =3;
    string sender_nickname=4;
    int64 send_at =5;
}

message JoinRequest {
    string sender_nickname =1;
    string room_id =2;
}

message JoinResponse {
  repeated string peers =1;
  string room_id =2;
}

message LeaveRequest {}

message LeaveResponse {
  bool success=1;
}




