FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o servidor ./main.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/servidor .

EXPOSE 6789

CMD ["./servidor"]